name: clean_k_chart_example
description: "A new Flutter project."
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ^3.13.0

dependencies:
  flutter:
    sdk: flutter
  clean_k_chart:
    path: ../clean_k_chart

dev_dependencies:
  flutter_lints: ^6.0.0

flutter:
  uses-material-design: true
